import type { Metadata } from 'next';
import './globals.css'; // Import global styles

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* You could add Header/Footer components here */}
        {children}
        {/* You could add Footer components here */}
      </body>
    </html>
  );
}